name: Build and Push Docker Image to Docker Hub

on:
    push:
        branches: [ "dev", "main" ]
    pull_request:
        branches: [ "dev", "main" ]

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: docker.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: krishnmohanseelam/streamlit-demo

jobs:

    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm 
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test the Docker image  
              run: docker-compose up -d 
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - 
              name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - 
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
    
            - 
              name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - 
              name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: krishnamohanseelam/streamlit-demo:latest
                